oi= open("tinpy.txt" , "w")
oi.write("sumthing is there \n") 
oi.close() 
ooi = open("tinpy.txt" , "a")
ooi.write ("this is new line\n ")
ooi.close()
io = open("tinpy.txt" , "r")
t = io.readlines()
print(t)
io.close()
